version: 0.1

phases:
  install:
    commands:
      - echo installing nodejs...
      - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
      - apt-get install -y nodejs
  pre_build:
    commands:
      - echo installing dependencies...
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
